version: '3.7'
services:
  db:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: always
    ports: 
      - 5432:5432
    environment:
     POSTGRES_USER: pguser
     POSTGRES_PASSWORD: pgpass